#!/bin/bash

install_dir="/opt/gp2c"

flags=""
code=false
output=false

while getopts ":co" opt; do
  case $opt in
    c)
      code=true
      ;;
		o)
      output=true
      ;;
  esac
done

for opt in $@
do
  flags="$flags $opt"
done
flags=${flags%"${BASH_ARGV[1]} ${BASH_ARGV[0]}"}

c="-c "
if [ $code ]; then
	flags="${flags//$c/}"
fi

if ! $output ; then
	flags="${flags}-o ./gp2_code_temp"
fi


echo "1. Making Code Directory"
echo "		mkdir -p ./gp2_code_temp"
mkdir -p ./gp2_code_temp
echo ""

echo "2. Executing GP2 Compiler on ${BASH_ARGV[1]}"
echo "		$install_dir/bin/gp2 $flags ${BASH_ARGV[1]}"
$install_dir/bin/gp2 $flags ${BASH_ARGV[1]}
echo ""

echo "3. Coping GP2 Library Files"
echo "		cp $install_dir/lib/*.{c,h} ./gp2_code_temp/"
cp $install_dir/lib/*.{c,h} ./gp2_code_temp/

echo "4. Building GP2 Executable"
echo "		make -C gp2_code_temp"
make -C gp2_code_temp
echo ""

echo "5. Executing on Host Graph ${BASH_ARGV[0]}"
echo "		gp2_code_temp/gp2run ${BASH_ARGV[0]}"
gp2_code_temp/gp2run ${BASH_ARGV[0]}
echo ""

if ! $code ; then
	echo "6. Removing code & executable & log"
	echo "		rm -r -f gp2_code_temp ; rm -f gp2.log"
	rm -r -f gp2_code_temp ; rm -f gp2.log
	echo ""
fi

echo "Final Result (stored in gp2.output) is:"
echo "		cat gp2.output"
cat gp2.output
